# this is the name of the workflow that will be displayed in the actions tab
name: CICD

on: 
  workflow_dispatch: 

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
       run: echo "code clone from GitHub"
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Container
       run:  echo "Docker Container Build"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
       run: echo "Testing the container"
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
       run: echo "Docker compose deployed the app"
      

  
